### ISSUE TITLE
Installation doubts

### ISSUE THREAD

**Issue by italoayres** [IncQueryLabs/ecoreDocGen#7]
Could you provide any further information on how to install this plugin? 
I've tried unzipping the entire project on droppings/ plugins/ and features/ folders on Eclipse Modeling Luna, but had no success. I'm new to plugin development btw.
Thank you.

**Comment by abelhegedus** [comment]
Hi,

the easiest way is to use the Eclipse Marketplace: https://marketplace.eclipse.org/content/ecore-documentation-generator (drag and drop the "Install" button to a view in your running Eclipse)

Otherwise, you can use the Release update site from https://github.com/IncQueryLabs/ecoreDocGen/wiki#downloads (use Help -> Install New Software)

**Comment by italoayres** [comment]
A pretty simple solution, thank you @abelhegedus . I'm getting the following error though.

The following solutions are not available: Ecore Documentation Generator 0.4.0 (id=hu.bme.mit.ecoredocgen.feature.feature.group, hu.bme.mit.ecoredocgen.validation.feature.feature.group, site=http://static.incquerylabs.com/projects/ecoredocgen/release/)

I've installed EcoreTools and EMF-IncQuery beforehand. Do you know what might be happening?

**Comment by italoayres** [comment]
Hmm, never mind. After trying a second time, even getting the same error, the installation appear to have worked. Thanks again.

**Comment by abelhegedus** [comment]
Thanks for reporting this, there was indeed a mistakenly left in dependency to EMF-IncQuery *1.1.0*, however, it should be removed.

I have uploaded a new version just now.
